version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
      day: friday
      time: '18:00'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 10
    reviewers:
      - s-weigand
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: friday
      time: '18:00'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 10
    reviewers:
      - s-weigand
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      day: friday
      time: '18:00'
      timezone: Europe/Amsterdam
