repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        # args: [--py36-plus]
  - repo: https://github.com/python/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: tv_pyremote/templates/index.html
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.0 # select a tag / sha to point at
    hooks:
      - id: curlylint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        exclude: ^docs
        additional_dependencies: [types-click, types-Flask, types-Jinja2]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: ^(docs|tests)
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-v]
        exclude: ^(docs|tests)
  - repo: https://github.com/myint/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b
    hooks:
      - id: rstcheck
        additional_dependencies: [rstcheck, sphinx]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        files: (.py|.rst)$
        args: [-L nnumber]

  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        name: Update interrogate badge
        args: [-v, -g, docs/_static]
        exclude: ^(docs|tests)
        always_run: true
        types: [python]
        stages: [push]
